### model
model_name_or_path: /mnt/data/0/LLM4Rec/llm_models/toys/llama3_lora_llm4rec_dpo_toys_1

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid  # [sigmoid (dpo), orpo, simpo]

### dataset
dataset: dpo_toys_2
template: llama3
cutoff_len: 8192
max_samples: 8399
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /mnt/data/0/LLM4Rec/LLaMA-Factory-main/saves/llama3-8b/lora/dpo/toys/llama3_lora_llm4rec_dpo_toys
logging_steps: 10
save_steps: 5000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.15 # 5%
fp16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
